#%RAML 0.8
title: Examplar
version: 0.0.1
baseUri: examplar.herokuapp.com/api
protocols: [HTTP, HTTPS]

/search:
    description: Queries the Question table for questions like the term entered.
    /{term}:
        displayName: Search Term
        get:
          queryParameters:
              pretty:
                default: false
                required: false
                displayName: Prettify
                description: prettifies JSON output.
                type: boolean
          responses:
            200:
              body:
                application/json:
                  example: |
                    {
                      "QuestionId": 7,
                      "QuestionNumber": 7,
                      "QuestionText": "Describe a method that can, without the use of binary addition, multiply any unsigned\r\nbinary integer by the binary number 10 (the denary number 2).",
                      "ExamPaperUnit": "COMP1",
                      "ExamPaperSeason": "Summer",
                      "ExamPaperDate": "2014-06-02T00:00:00.000Z",
                      "ExamBoardName": "AQA",
                      "LevelTitle": "AS",
                      "SubjectTitle": "Computing"
                    }
        uriParameters:
            term:
                default: ''
                required: true
                type: string
                displayName: Search Term
                description: The search term used in the SQL query to get questions like {term}




/result:
  description: Fetches result based upon an ID parsed.
  /{id}:
      displayName: Search Term
      get:
        queryParameters:
            pretty:
              default: false
              required: false
              displayName: Prettify
              description: prettifies JSON output.
              type: boolean
        responses:
          200:
            body:
              application/json:
      uriParameters:
          id:
              default: ''
              required: true
              type: integer
              displayName: Result ID
              description: The ID used SQL query to get a question
/image:
  /{id}:

/more:
  /{id}:

/related:
  /{id}:

/examiner:
  /{id}:

/filter:
  /level:
  /examboard:
  /subject:
